version: '3.7'


services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    networks:
      - backbone
    volumes:
      - '/opt/wireguard/client/config:/config:z'
      - '/lib/modules:/lib/modules:ro'
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - "localhost:8112"
    command: 
      bash -c "echo 'nameserver 10.64.0.1' >> /etc/resolv.conf
      && echo
      && ..."



networks:
  backbone:
    name: backbone
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:a::/64
          gateway: 2001:db8:a::1
